name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd TestCase3
        npm install

    - name: Build Docker image
      run: |
        cd TestCase4
        docker build -t nodejs-api .

    - name: Deploy application
      run: echo "Deploying application to server..."